/*
 * Marqo
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AnyOfValidationErrorLocItems model module.
 * @module model/AnyOfValidationErrorLocItems
 * @version 0.2.0
 */
export class AnyOfValidationErrorLocItems {
  /**
   * Constructs a new <code>AnyOfValidationErrorLocItems</code>.
   * @alias module:model/AnyOfValidationErrorLocItems
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnyOfValidationErrorLocItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnyOfValidationErrorLocItems} obj Optional instance to populate.
   * @return {module:model/AnyOfValidationErrorLocItems} The populated <code>AnyOfValidationErrorLocItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnyOfValidationErrorLocItems();
    }
    return obj;
  }
}
