/*
 * Marqo
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SearchQuery model module.
 * @module model/SearchQuery
 * @version 0.2.0
 */
export class SearchQuery {
  /**
   * Constructs a new <code>SearchQuery</code>.
   * @alias module:model/SearchQuery
   * @class
   * @param q {String} 
   */
  constructor(q) {
    this.q = q;
  }

  /**
   * Constructs a <code>SearchQuery</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchQuery} obj Optional instance to populate.
   * @return {module:model/SearchQuery} The populated <code>SearchQuery</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchQuery();
      if (data.hasOwnProperty('filter'))
        obj.filter = ApiClient.convertToType(data['filter'], 'String');
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
      if (data.hasOwnProperty('q'))
        obj.q = ApiClient.convertToType(data['q'], 'String');
      if (data.hasOwnProperty('reRanker'))
        obj.reRanker = ApiClient.convertToType(data['reRanker'], 'String');
      if (data.hasOwnProperty('searchMethod'))
        obj.searchMethod = ApiClient.convertToType(data['searchMethod'], 'String');
      if (data.hasOwnProperty('searchableAttributes'))
        obj.searchableAttributes = ApiClient.convertToType(data['searchableAttributes'], ['String']);
      if (data.hasOwnProperty('showHighlights'))
        obj.showHighlights = ApiClient.convertToType(data['showHighlights'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} filter
 */
SearchQuery.prototype.filter = undefined;

/**
 * @member {Number} limit
 * @default 10
 */
SearchQuery.prototype.limit = 10;

/**
 * @member {String} q
 */
SearchQuery.prototype.q = undefined;

/**
 * @member {String} reRanker
 */
SearchQuery.prototype.reRanker = undefined;

/**
 * @member {String} searchMethod
 * @default 'NEURAL'
 */
SearchQuery.prototype.searchMethod = 'NEURAL';

/**
 * @member {Array.<String>} searchableAttributes
 */
SearchQuery.prototype.searchableAttributes = undefined;

/**
 * @member {Boolean} showHighlights
 * @default true
 */
SearchQuery.prototype.showHighlights = true;

