/*
 * Marqo
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {HTTPValidationError} from '../model/HTTPValidationError';
import {SearchQuery} from '../model/SearchQuery';

/**
* Default service.
* @module api/DefaultApi
* @version 0.2.0
*/
export class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addDocumentsIndexesIndexNameDocumentsPost operation.
     * @callback moduleapi/DefaultApi~addDocumentsIndexesIndexNameDocumentsPostCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Documents
     * add_documents endpoint
     * @param {Array.<Object>} body 
     * @param {String} indexName 
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.refresh  (default to <.>)
     * @param {Number} opts.batchSize  (default to <.>)
     * @param {Number} opts.processes  (default to <.>)
     * @param {module:api/DefaultApi~addDocumentsIndexesIndexNameDocumentsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    addDocumentsIndexesIndexNameDocumentsPost(body, indexName, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addDocumentsIndexesIndexNameDocumentsPost");
      }
      // verify the required parameter 'indexName' is set
      if (indexName === undefined || indexName === null) {
        throw new Error("Missing the required parameter 'indexName' when calling addDocumentsIndexesIndexNameDocumentsPost");
      }

      let pathParams = {
        'index_name': indexName
      };
      let queryParams = {
        'refresh': opts['refresh'],'batch_size': opts['batchSize'],'processes': opts['processes']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBasic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/indexes/{index_name}/documents', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the createIndexIndexesIndexNamePost operation.
     * @callback moduleapi/DefaultApi~createIndexIndexesIndexNamePostCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Index
     * @param {String} indexName 
     * @param {Object} opts Optional parameters
     * @param {Object} opts.body 
     * @param {module:api/DefaultApi~createIndexIndexesIndexNamePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createIndexIndexesIndexNamePost(indexName, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'indexName' is set
      if (indexName === undefined || indexName === null) {
        throw new Error("Missing the required parameter 'indexName' when calling createIndexIndexesIndexNamePost");
      }

      let pathParams = {
        'index_name': indexName
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBasic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/indexes/{index_name}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the deleteDocsIndexesIndexNameDocumentsDeleteBatchPost operation.
     * @callback moduleapi/DefaultApi~deleteDocsIndexesIndexNameDocumentsDeleteBatchPostCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Docs
     * @param {Array.<String>} body 
     * @param {String} indexName 
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.refresh  (default to <.>)
     * @param {module:api/DefaultApi~deleteDocsIndexesIndexNameDocumentsDeleteBatchPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    deleteDocsIndexesIndexNameDocumentsDeleteBatchPost(body, indexName, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling deleteDocsIndexesIndexNameDocumentsDeleteBatchPost");
      }
      // verify the required parameter 'indexName' is set
      if (indexName === undefined || indexName === null) {
        throw new Error("Missing the required parameter 'indexName' when calling deleteDocsIndexesIndexNameDocumentsDeleteBatchPost");
      }

      let pathParams = {
        'index_name': indexName
      };
      let queryParams = {
        'refresh': opts['refresh']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBasic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/indexes/{index_name}/documents/delete-batch', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the deleteIndexIndexesIndexNameDelete operation.
     * @callback moduleapi/DefaultApi~deleteIndexIndexesIndexNameDeleteCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Index
     * @param {String} indexName 
     * @param {module:api/DefaultApi~deleteIndexIndexesIndexNameDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    deleteIndexIndexesIndexNameDelete(indexName, callback) {
      
      let postBody = null;
      // verify the required parameter 'indexName' is set
      if (indexName === undefined || indexName === null) {
        throw new Error("Missing the required parameter 'indexName' when calling deleteIndexIndexesIndexNameDelete");
      }

      let pathParams = {
        'index_name': indexName
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBasic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/indexes/{index_name}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getDocumentByIdIndexesIndexNameDocumentsDocumentIdGet operation.
     * @callback moduleapi/DefaultApi~getDocumentByIdIndexesIndexNameDocumentsDocumentIdGetCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Document By Id
     * @param {String} indexName 
     * @param {String} documentId 
     * @param {module:api/DefaultApi~getDocumentByIdIndexesIndexNameDocumentsDocumentIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getDocumentByIdIndexesIndexNameDocumentsDocumentIdGet(indexName, documentId, callback) {
      
      let postBody = null;
      // verify the required parameter 'indexName' is set
      if (indexName === undefined || indexName === null) {
        throw new Error("Missing the required parameter 'indexName' when calling getDocumentByIdIndexesIndexNameDocumentsDocumentIdGet");
      }
      // verify the required parameter 'documentId' is set
      if (documentId === undefined || documentId === null) {
        throw new Error("Missing the required parameter 'documentId' when calling getDocumentByIdIndexesIndexNameDocumentsDocumentIdGet");
      }

      let pathParams = {
        'index_name': indexName,'document_id': documentId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBasic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/indexes/{index_name}/documents/{document_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getIndexStatsIndexesIndexNameStatsGet operation.
     * @callback moduleapi/DefaultApi~getIndexStatsIndexesIndexNameStatsGetCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Index Stats
     * @param {String} indexName 
     * @param {module:api/DefaultApi~getIndexStatsIndexesIndexNameStatsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getIndexStatsIndexesIndexNameStatsGet(indexName, callback) {
      
      let postBody = null;
      // verify the required parameter 'indexName' is set
      if (indexName === undefined || indexName === null) {
        throw new Error("Missing the required parameter 'indexName' when calling getIndexStatsIndexesIndexNameStatsGet");
      }

      let pathParams = {
        'index_name': indexName
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBasic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/indexes/{index_name}/stats', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the refreshIndexIndexesIndexNameRefreshPost operation.
     * @callback moduleapi/DefaultApi~refreshIndexIndexesIndexNameRefreshPostCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Refresh Index
     * @param {String} indexName 
     * @param {module:api/DefaultApi~refreshIndexIndexesIndexNameRefreshPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    refreshIndexIndexesIndexNameRefreshPost(indexName, callback) {
      
      let postBody = null;
      // verify the required parameter 'indexName' is set
      if (indexName === undefined || indexName === null) {
        throw new Error("Missing the required parameter 'indexName' when calling refreshIndexIndexesIndexNameRefreshPost");
      }

      let pathParams = {
        'index_name': indexName
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBasic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/indexes/{index_name}/refresh', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the rootGet operation.
     * @callback moduleapi/DefaultApi~rootGetCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Root
     * @param {module:api/DefaultApi~rootGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    rootGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the searchIndexesIndexNameSearchPost operation.
     * @callback moduleapi/DefaultApi~searchIndexesIndexNameSearchPostCallback
     * @param {String} error Error message, if any.
     * @param {Object{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search
     * @param {module:model/SearchQuery} body 
     * @param {String} indexName 
     * @param {module:api/DefaultApi~searchIndexesIndexNameSearchPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    searchIndexesIndexNameSearchPost(body, indexName, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling searchIndexesIndexNameSearchPost");
      }
      // verify the required parameter 'indexName' is set
      if (indexName === undefined || indexName === null) {
        throw new Error("Missing the required parameter 'indexName' when calling searchIndexesIndexNameSearchPost");
      }

      let pathParams = {
        'index_name': indexName
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['HTTPBasic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;

      return this.apiClient.callApi(
        '/indexes/{index_name}/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}