/*
 * Marqo
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Marqo);
  }
}(this, function(expect, Marqo) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Marqo.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('addDocumentsIndexesIndexNameDocumentsPost', function() {
        it('should call addDocumentsIndexesIndexNameDocumentsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for addDocumentsIndexesIndexNameDocumentsPost call and complete the assertions
          /*
          var opts = {};

          instance.addDocumentsIndexesIndexNameDocumentsPost(body, indexName, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createIndexIndexesIndexNamePost', function() {
        it('should call createIndexIndexesIndexNamePost successfully', function(done) {
          // TODO: uncomment, update parameter values for createIndexIndexesIndexNamePost call and complete the assertions
          /*
          var opts = {};

          instance.createIndexIndexesIndexNamePost(indexName, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteDocsIndexesIndexNameDocumentsDeleteBatchPost', function() {
        it('should call deleteDocsIndexesIndexNameDocumentsDeleteBatchPost successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteDocsIndexesIndexNameDocumentsDeleteBatchPost call and complete the assertions
          /*
          var opts = {};

          instance.deleteDocsIndexesIndexNameDocumentsDeleteBatchPost(body, indexName, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteIndexIndexesIndexNameDelete', function() {
        it('should call deleteIndexIndexesIndexNameDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteIndexIndexesIndexNameDelete call and complete the assertions
          /*

          instance.deleteIndexIndexesIndexNameDelete(indexName, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDocumentByIdIndexesIndexNameDocumentsDocumentIdGet', function() {
        it('should call getDocumentByIdIndexesIndexNameDocumentsDocumentIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for getDocumentByIdIndexesIndexNameDocumentsDocumentIdGet call and complete the assertions
          /*

          instance.getDocumentByIdIndexesIndexNameDocumentsDocumentIdGet(indexName, documentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getIndexStatsIndexesIndexNameStatsGet', function() {
        it('should call getIndexStatsIndexesIndexNameStatsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for getIndexStatsIndexesIndexNameStatsGet call and complete the assertions
          /*

          instance.getIndexStatsIndexesIndexNameStatsGet(indexName, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('refreshIndexIndexesIndexNameRefreshPost', function() {
        it('should call refreshIndexIndexesIndexNameRefreshPost successfully', function(done) {
          // TODO: uncomment, update parameter values for refreshIndexIndexesIndexNameRefreshPost call and complete the assertions
          /*

          instance.refreshIndexIndexesIndexNameRefreshPost(indexName, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('rootGet', function() {
        it('should call rootGet successfully', function(done) {
          // TODO: uncomment rootGet call and complete the assertions
          /*

          instance.rootGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('searchIndexesIndexNameSearchPost', function() {
        it('should call searchIndexesIndexNameSearchPost successfully', function(done) {
          // TODO: uncomment, update parameter values for searchIndexesIndexNameSearchPost call and complete the assertions
          /*

          instance.searchIndexesIndexNameSearchPost(body, indexName, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
